### ISSUE TITLE
Cannot load in PIP

### ISSUE THREAD

**Issue by cyberpsychosis** [flagist0/pypavlok#2]
Unable to install with pip:

Running Debian Jessie/Linux

--Error---

Collecting pypavlok
Collecting gattlib>=0.20150805 (from pypavlok)
  Using cached gattlib-0.20150805.tar.gz
Building wheels for collected packages: gattlib
  Running setup.py bdist_wheel for gattlib ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-F8pfzu/gattlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /tmp/tmpF9nvwqpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'gattlib' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  creating build/temp.linux-x86_64-2.7/src/bluez
  creating build/temp.linux-x86_64-2.7/src/bluez/lib
  creating build/temp.linux-x86_64-2.7/src/bluez/attrib
  creating build/temp.linux-x86_64-2.7/src/bluez/src
  creating build/temp.linux-x86_64-2.7/src/bluez/src/shared
  creating build/temp.linux-x86_64-2.7/src/bluez/btio
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Isrc/bluez -I/usr/include/python2.7 -c src/gattservices.cpp -o build/temp.linux-x86_64-2.7/src/gattservices.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  src/gattservices.cpp:6:33: fatal error: bluetooth/bluetooth.h: No such file or directory
   #include <bluetooth/bluetooth.h>
                                   ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

  Failed building wheel for gattlib
  Running setup.py clean for gattlib
Failed to build gattlib
Installing collected packages: gattlib, pypavlok
  Running setup.py install for gattlib ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-F8pfzu/gattlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-nrKxMe-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'gattlib' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    creating build/temp.linux-x86_64-2.7/src/bluez
    creating build/temp.linux-x86_64-2.7/src/bluez/lib
    creating build/temp.linux-x86_64-2.7/src/bluez/attrib
    creating build/temp.linux-x86_64-2.7/src/bluez/src
    creating build/temp.linux-x86_64-2.7/src/bluez/src/shared
    creating build/temp.linux-x86_64-2.7/src/bluez/btio
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Isrc/bluez -I/usr/include/python2.7 -c src/gattservices.cpp -o build/temp.linux-x86_64-2.7/src/gattservices.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/gattservices.cpp:6:33: fatal error: bluetooth/bluetooth.h: No such file or directory
     #include <bluetooth/bluetooth.h>
                                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
----------------------------------------
```

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-F8pfzu/gattlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-nrKxMe-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-F8pfzu/gattlib

**Comment by flagist0** [comment]
Hello @cyberpsychosis!
The problem is with pygattlib -- it is not a pure Python package and it has external dependencies, that have to be resolved by user.
You'll have to install its dependencies listed in this file: https://bitbucket.org/OscarAcena/pygattlib/src/ba669d2914c04275901772a19ed6238d58691dff/DEPENDS?fileviewer=file-view-default or install it 'Debian way': https://bitbucket.org/OscarAcena/pygattlib#markdown-header-debian-way

**Comment by cyberpsychosis** [comment]
Thanks for the fast response, however
Installing it the debian way resulted in the following error:

pip install pypavlok
Collecting pypavlok
Collecting gattlib>=0.20150805 (from pypavlok)
  Using cached gattlib-0.20150805.tar.gz
Building wheels for collected packages: gattlib
  Running setup.py bdist_wheel for gattlib ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-gW7gzx/gattlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /tmp/tmp2_bQ5Apip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'gattlib' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  creating build/temp.linux-x86_64-2.7/src/bluez
  creating build/temp.linux-x86_64-2.7/src/bluez/lib
  creating build/temp.linux-x86_64-2.7/src/bluez/attrib
  creating build/temp.linux-x86_64-2.7/src/bluez/src
  creating build/temp.linux-x86_64-2.7/src/bluez/src/shared
  creating build/temp.linux-x86_64-2.7/src/bluez/btio
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Isrc/bluez -I/usr/include/python2.7 -c src/gattservices.cpp -o build/temp.linux-x86_64-2.7/src/gattservices.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  src/gattservices.cpp:6:33: fatal error: bluetooth/bluetooth.h: No such file or directory
   #include <bluetooth/bluetooth.h>
                                   ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

  Failed building wheel for gattlib
  Running setup.py clean for gattlib
Failed to build gattlib
Installing collected packages: gattlib, pypavlok
  Found existing installation: gattlib 0.20150130
    DEPRECATION: Uninstalling a distutils installed project (gattlib) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling gattlib-0.20150130:
      Successfully uninstalled gattlib-0.20150130
  Running setup.py install for gattlib ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-gW7gzx/gattlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-HAQFrs-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'gattlib' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    creating build/temp.linux-x86_64-2.7/src/bluez
    creating build/temp.linux-x86_64-2.7/src/bluez/lib
    creating build/temp.linux-x86_64-2.7/src/bluez/attrib
    creating build/temp.linux-x86_64-2.7/src/bluez/src
    creating build/temp.linux-x86_64-2.7/src/bluez/src/shared
    creating build/temp.linux-x86_64-2.7/src/bluez/btio
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DVERSION="5.25" -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Isrc/bluez -I/usr/include/python2.7 -c src/gattservices.cpp -o build/temp.linux-x86_64-2.7/src/gattservices.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/gattservices.cpp:6:33: fatal error: bluetooth/bluetooth.h: No such file or directory
     #include <bluetooth/bluetooth.h>
                                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
----------------------------------------
```

  Rolling back uninstall of gattlib
Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-gW7gzx/gattlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-HAQFrs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-gW7gzx/gattlib

**Comment by flagist0** [comment]
Do you have bluez installed? Also it looks like you'll need libbluetooth-dev package to provide that header from your log

**Comment by cyberpsychosis** [comment]
You sir... are a scholar and a gentlemen.
Yeah I had bluez/libbluetooth 5.23 running but my issue was solved by installing libbluetooth-dev

Thanks again for your help and your awesome contribution to the community!

**Comment by cyberpsychosis** [comment]
That was it! Thank you so much.
